version: 2.1
jobs:
  build:
    working_directory: ~/kylo
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.1
      - image: mongo:4.2.2
      # Specify service dependencies here if necessary
    steps:
      - checkout
      - run:
          name: Ensure npm is running
          command: sudo npm install -g npm
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: setting up npm
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          command: npm run circle
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit"
      - store_test_results:
          path: reports/junit

